parameters:
    app.database_user: '%env(DATABASE_USER)%'
    app.database_password: '%env(DATABASE_PASSWORD)%'
    app.database_name: '%env(DATABASE_NAME)%'
    app.database_host: '%env(DATABASE_HOST)%'
    app.gnd_window: 20

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Efi\GndViewerBundle\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
